[package]
name = "minitarp"
version = "0.1.0"
authors = ["xd009642 <danielmckenna93@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.31.2"
libc = "*"
serde = {version="1.0", features=["derive"]}
serde_json = "1.0"
gnuplot = "0.0.37"
